version: '3.7'

services:
  ner:
    image: gretelai/ner
    environment:
      GRETEL_API_KEY: grtuXXX
    restart: always
    networks:
      - "gretel"
    volumes:
      - ./config.yml:/etc/gretel/config.yml:ro
      - ./codewords.txt:/etc/gretel/codewords.txt:ro
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ner
    ports:
      - 8000:80
    networks:
      - "gretel"

networks:
  gretel:
